import { test, expect } from '@playwright/test';

test('desktop: plateau, achat, sauvegarde et atelier', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.setViewportSize({ width: 1440, height: 1080 });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Votre nation', exact: true })).toBeVisible();
  await page.screenshot({ path: '.artifacts/desktop.jpg', fullPage: true });
  await page.getByRole('button', { name: 'Révéler la première tuile' }).click();
  const resolve = page.getByRole('button', { name: 'Valider', exact: true });
  if (await resolve.isVisible()) await resolve.click();
  await page.getByRole('button', { name: /Revenus/ }).click();
  await page.getByRole('button', { name: 'Centrale au fioul, 100 euros', exact: true }).click();
  await page.getByTestId('slot-b1').click();
  await expect(page.getByTestId('slot-b1')).toContainText('Centrale au fioul');
  let staged = await page.evaluate(() => JSON.parse(localStorage.getItem('prosperity.game.v1')!));
  expect(staged.board.b1).toBeNull();
  expect(staged.plannedActions).toHaveLength(2);
  await expect(page.getByRole('button', { name: 'Valider le tour', exact: true })).toBeEnabled();
  await page.screenshot({ path: '.artifacts/desktop-planned.jpg', fullPage: true });
  await page.reload();
  await expect(page.getByTestId('slot-b1')).toContainText('Centrale au fioul');
  await page.getByRole('button', { name: 'Annuler la dernière action', exact: true }).click();
  await expect(page.getByTestId('slot-b1')).not.toContainText('Centrale au fioul');
  await expect(page.getByRole('button', { name: 'Valider le tour', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Centrale au fioul, 100 euros', exact: true }).click();
  await page.getByTestId('slot-b1').click();
  await page.getByRole('button', { name: 'Valider le tour', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Tour suivant', exact: true })).toBeEnabled();
  staged = await page.evaluate(() => JSON.parse(localStorage.getItem('prosperity.game.v1')!));
  expect(staged.board.b1.id).toBe('initial-20');
  expect(staged.plannedActions).toEqual([]);
  expect(staged.phase).toBe('committed');
  await page.getByRole('button', { name: 'Atelier de tuiles', exact: true }).click();
  await page.screenshot({ path: '.artifacts/editor.jpg', fullPage: false });
  await page.getByRole('button', { name: 'Nouvelle tuile', exact: true }).click();
  await page.getByRole('textbox', { name: 'Nom de la tuile' }).fill('Forêt expérimentale');
  await page.getByRole('spinbutton', { name: 'Valeur Écologie' }).fill('3');
  await page.getByRole('button', { name: 'Enregistrer la tuile' }).click();
  await expect(page.getByRole('status')).toContainText('Tuile enregistrée');
  await page.reload();
  await page.getByRole('button', { name: 'Atelier de tuiles', exact: true }).click();
  await page.getByRole('textbox', { name: 'Rechercher dans la collection' }).fill('Forêt expérimentale');
  await expect(page.getByRole('button', { name: 'Forêt expérimentale', exact: true })).toBeVisible();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Exporter', exact: true }).click();
  expect((await download).suggestedFilename()).toBe('prosperity-catalogue.json');
  await page.getByRole('button', { name: 'La partie', exact: true }).click();
  await expect(page.getByRole('button', { name: /^Forêt expérimentale,/ })).toHaveCount(0);
  expect(errors).toEqual([]);
});

test('mobile: affichage sans débordement, navigation et actions', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.screenshot({ path: '.artifacts/mobile.jpg', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Révéler la première tuile' }).click();
  if (await page.getByRole('button', { name: 'Valider', exact: true }).isVisible()) await page.getByRole('button', { name: 'Valider', exact: true }).click();
  const before = await page.evaluate(() => JSON.parse(localStorage.getItem('prosperity.game.v1')!));
  await page.getByRole('button', { name: 'Rechercher en énergie : avancer d’une case' }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: /Dépolluer/ }).filter({ visible: true }).first().click();
  await expect(page.getByRole('button', { name: 'Valider le tour', exact: true })).toBeEnabled();
  await page.screenshot({ path: '.artifacts/mobile-planned.jpg', fullPage: true });
  await page.getByRole('button', { name: 'Annuler les deux actions' }).click();
  await expect(page.getByTestId('pollution-preview')).toHaveText(`${before.pollution}`);
  await expect(page.getByRole('button', { name: 'Valider le tour', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Rechercher en écologie : avancer d’une case' }).click();
  await page.getByRole('tab', { name: /Marché/ }).click();
  await expect(page.getByRole('region', { name: 'Marché des technologies' })).toBeVisible();
  await page.getByRole('tab', { name: 'Plateau', exact: true }).click();
  await page.getByRole('button', { name: /Revenus/ }).click();
  await page.getByRole('button', { name: 'Valider le tour', exact: true }).click();
  const after = await page.evaluate(() => JSON.parse(localStorage.getItem('prosperity.game.v1')!));
  expect(after.research.energy).toBe(before.research.energy);
  expect(after.research.ecology).toBe(before.research.ecology + 1);
  expect(after.money).toBe(before.money + 100);
  expect(after.pollution).toBe(before.pollution);
  await page.getByRole('button', { name: 'Atelier de tuiles', exact: true }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: '.artifacts/editor-mobile.jpg', fullPage: true });
  await page.getByRole('button', { name: 'Règles du jeu', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'La version solo' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});

test('une partie entière jusqu’au score final et au record', async ({ page }) => {
  await page.goto('/');
  for (let step = 0; step < 220; step++) {
    const g = await page.evaluate(() => JSON.parse(localStorage.getItem('prosperity.game.v1')!));
    if (g.phase === 'finished') break;
    if (g.phase === 'energy' || g.phase === 'research') await page.getByRole('button', { name: 'Valider', exact: true }).click();
    else if (g.phase === 'final') await page.getByRole('button', { name: /^Décompter :/ }).click();
    else if (g.phase === 'draw') await page.getByRole('button', { name: 'Révéler la première tuile' }).click();
    else if (g.phase === 'committed') await page.getByRole('button', { name: g.deck.length ? 'Tour suivant' : 'Décompte final', exact: true }).click();
    else if (g.plannedActions.length === g.actions) await page.getByRole('button', { name: 'Valider le tour', exact: true }).click();
    else if (g.pollution > g.plannedActions.filter((a: { type: string }) => a.type === 'cleanup').length) await page.getByRole('button', { name: /Dépolluer/ }).first().click();
    else await page.getByRole('button', { name: /Revenus/ }).click();
  }
  await expect(page.getByRole('heading', { name: /points de prospérité/ })).toBeVisible();
  const state = await page.evaluate(() => JSON.parse(localStorage.getItem('prosperity.game.v1')!));
  expect(state.turn).toBe(36);
  expect(state.phase).toBe('finished');
  expect(state.score).toBeGreaterThan(0);
  await page.screenshot({ path: '.artifacts/finished.jpg', fullPage: true });
  await page.reload();
  await expect(page.getByRole('heading', { name: /points de prospérité/ })).toBeVisible();
  await page.getByRole('button', { name: /Votre meilleur score/ }).click();
  await expect(page.getByRole('dialog')).toContainText('Classique');
});

test('catalogue personnalisé: modification, import validé et nouvelle partie', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/');
  await page.getByRole('button', { name: 'Atelier de tuiles', exact: true }).click();
  await page.getByRole('spinbutton', { name: 'Valeur Écologie' }).fill('3');
  await page.getByRole('button', { name: 'Enregistrer la tuile' }).click();
  await expect(page.getByRole('status')).toContainText('Tuile enregistrée');
  await expect(page.locator('.editor-preview .composed-tile')).toBeVisible();
  await page.screenshot({ path: '.artifacts/custom-editor.jpg', fullPage: false });
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('prosperity.catalog.v1')!));
  expect(saved[0].ecology).toBe(3);
  await page.getByLabel('Importer un catalogue JSON').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify([{ ...saved[0], category: '__proto__' }])) });
  await expect(page.getByRole('alert')).toContainText('Import impossible');
  await page.getByLabel('Importer un catalogue JSON').setInputFiles({ name: 'valid.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ version: 1, tiles: saved })) });
  await expect(page.getByRole('dialog')).toContainText('60 tuiles');
  await page.getByRole('button', { name: 'Importer ce catalogue' }).click();
  await page.getByRole('button', { name: 'Nouvelle partie', exact: true }).click();
  await page.getByRole('dialog').getByRole('checkbox').check();
  await page.getByRole('textbox', { name: 'Graine du mélange' }).fill('catalogue-test');
  await page.getByRole('button', { name: 'Fonder ma nation' }).click();
  await expect(page.locator('.play-edition')).toContainText('Partie personnalisée');
  const g = await page.evaluate(() => JSON.parse(localStorage.getItem('prosperity.game.v1')!));
  expect(g.catalog[0].ecology).toBe(3);
  expect(g.totalTurns).toBe(36);
  await page.getByRole('button', { name: 'Atelier de tuiles', exact: true }).click();
  await page.locator('img').evaluateAll(images => images.forEach(img => img.loading = 'eager'));
  await page.waitForFunction(() => [...document.images].every(img => img.complete && img.naturalWidth > 0));
});

test('dimensions variées et absence de débordements', async ({ page }) => {
  await page.goto('/');
  for (const width of [320, 768, 1024, 1920]) {
    await page.setViewportSize({ width, height: 900 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `largeur ${width}`).toBe(true);
    await page.getByRole('button', { name: 'Atelier de tuiles', exact: true }).click();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `atelier ${width}`).toBe(true);
    await page.getByRole('button', { name: 'La partie', exact: true }).click();
  }
});

test('illustration personnalisée: cinq symboles, aperçu, export et partie', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/');
  await page.getByRole('button', { name: 'Atelier de tuiles', exact: true }).click();
  await page.getByRole('button', { name: 'Nouvelle tuile', exact: true }).click();
  await page.getByRole('textbox', { name: 'Nom de la tuile' }).fill('Ville expérimentale');
  await page.getByLabel('Importer une illustration').setInputFiles('public/assets/city.jpg');
  const values = [['Énergie', '-2'], ['Écologie', '3'], ['Capital', '2'], ['Recherche', '1'], ['Prospérité', '2']];
  for (const [label, value] of values) await page.getByRole('spinbutton', { name: `Valeur ${label}` }).fill(value);
  const art = page.locator('.editor-preview .composed-tile');
  for (const symbol of ['energy', 'ecology', 'capital', 'research', 'prosperity']) await expect(art.locator(`[data-symbol="${symbol}"]`)).toBeVisible();
  await expect(art.locator('[data-symbol="energy"]')).toHaveText('-2');
  await expect(art.locator('[data-symbol="energy"]')).toHaveClass(/negative/);
  await page.getByRole('spinbutton', { name: 'Valeur Énergie' }).fill('0');
  await expect(art.locator('[data-symbol="energy"]')).toHaveCount(0);
  await page.getByRole('spinbutton', { name: 'Valeur Énergie' }).fill('-2');
  await page.getByRole('checkbox', { name: 'Symboles sur l’illustration' }).uncheck();
  await expect(art.locator('.art-symbol')).toHaveCount(0);
  await page.getByRole('checkbox', { name: 'Symboles sur l’illustration' }).check();
  await expect(art.locator('.art-symbol')).toHaveCount(5);
  await page.getByRole('button', { name: 'Enregistrer la tuile' }).click();
  await page.screenshot({ path: '.artifacts/five-symbols-editor.jpg', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await art.scrollIntoViewIfNeeded();
  await page.screenshot({ path: '.artifacts/five-symbols-mobile.jpg', fullPage: false });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('prosperity.catalog.v1')!));
  const tile = saved.find((t: { name: string }) => t.name === 'Ville expérimentale');
  expect(tile.symbolsOnImage).toBe(true);
  expect(tile.image).toMatch(/^data:image\/jpeg;base64,/);
  const exported = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Exporter', exact: true }).click();
  const path = await (await exported).path();
  expect(path).toBeTruthy();
  await page.getByLabel('Importer un catalogue JSON').setInputFiles(path!);
  await page.getByRole('button', { name: 'Importer ce catalogue' }).click();
  await page.reload();
  await page.getByRole('button', { name: 'Nouvelle partie', exact: true }).click();
  await page.getByRole('dialog').getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Fonder ma nation' }).click();
  const card = page.getByRole('button', { name: /^Ville expérimentale,/ });
  await expect(card.locator('.art-symbol')).toHaveCount(5);
  await card.scrollIntoViewIfNeeded();
  const overflowing = await card.locator('.art-symbol').evaluateAll(symbols => symbols.some(symbol => {
    const outer = symbol.closest('.tile-art')!.getBoundingClientRect();
    const rect = symbol.getBoundingClientRect();
    return rect.left < outer.left || rect.right > outer.right || rect.bottom > outer.bottom;
  }));
  expect(overflowing).toBe(false);
  await page.getByRole('button', { name: 'Révéler la première tuile' }).click();
  if (await page.getByRole('button', { name: 'Valider', exact: true }).isVisible()) await page.getByRole('button', { name: 'Valider', exact: true }).click();
  await card.click();
  await page.getByTestId('slot-a2').click();
  const placed = page.getByTestId('slot-a2');
  await expect(placed.locator('.art-symbol')).toHaveCount(5);
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    const outside = await placed.locator('.art-symbol').evaluateAll(symbols => symbols.some(symbol => {
      const bounds = symbol.closest('.tile-art')!.getBoundingClientRect();
      const rect = symbol.getBoundingClientRect();
      return rect.left < bounds.left || rect.right > bounds.right || rect.bottom > bounds.bottom;
    }));
    expect(outside, `symboles sur le plateau à ${width}px`).toBe(false);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '.artifacts/custom-mobile-board.jpg' });
  await placed.click();
  await expect(page.getByRole('dialog').locator('.art-symbol')).toHaveCount(5);
  await expect(page.getByRole('dialog').locator('[data-symbol="energy"] b')).toBeVisible();
});
