import { ExternalLink, BookOpen, Globe2, Leaf, FlaskConical, Coins, Zap } from 'lucide-react';

export default function Rules() {
  return <article className="rules-page"><div className="page-heading"><div><span className="eyebrow">LE LIVRET</span><h1>Règles du jeu</h1></div><a className="secondary" href="/bb-prosperity-rulebook.pdf" target="_blank" rel="noreferrer"><BookOpen size={16} />Livret original<ExternalLink size={14} /></a></div>
    <div className="rules-intro"><Globe2 size={42} strokeWidth={1.2} /><p>De 1970 à 2030, développez votre nation, financez la recherche et préservez votre environnement. Votre objectif : accumuler le plus de points de prospérité.</p></div>
    <section><h2>La version solo</h2><p>Le livret fourni ne contient pas de règle solo. Cette adaptation propose un défi de score : vous jouez les 36 tours et réalisez deux actions à chaque tour. Les règles de construction et de décompte sont conservées. Le classement final de recherche entre joueurs est supprimé, donc aucun bonus de 3 ou 1 point n’est attribué. Vos records classiques et personnalisés sont distingués.</p><p>Le plateau argent reproduit la mise en place illustrée : 100 €, 8 pollutions, un bilan énergétique de +1 et écologique de -1, un symbole capital et un symbole recherche. La face noire n’étant pas illustrée dans le document, cette version utilise le pays argent.</p></section>
    <section><h2>Un tour de jeu</h2><ol><li><strong>Révélez une technologie.</strong> Son symbole déclenche immédiatement le décompte correspondant sur votre plateau. Répartissez la recherche ou réglez un déficit énergétique si nécessaire. La tuile rejoint le marché.</li><li><strong>Préparez deux actions.</strong> Vous pouvez choisir deux fois la même : percevoir 100 €, retirer une pollution, avancer d’une case de recherche ou acheter une technologie.</li><li><strong>Validez le tour.</strong> Les deux actions deviennent définitives. Avant validation, elles peuvent être annulées ensemble ou une par une, y compris après avoir rechargé la partie. Passez ensuite au tour suivant. Chaque décennie comporte les cinq décomptes dans un ordre mélangé. En 2030, une sixième tuile déclenche un second décompte de prospérité.</li></ol></section>
    <section><h2>Les cinq décomptes</h2><div className="rules-tallies"><div><Zap /><h3>Énergie</h3><p>Chaque énergie positive rapporte 50 €. Pour chaque énergie négative, payez 100 € ou ajoutez une pollution, en combinant librement les deux.</p></div><div><Leaf /><h3>Écologie</h3><p>Chaque écologie positive retire une pollution ; l’excédent rapporte 50 € par unité. Chaque écologie négative ajoute une pollution.</p></div><div><Coins /><h3>Capital</h3><p>Recevez 100 € par symbole capital visible sur votre plateau.</p></div><div><FlaskConical /><h3>Recherche</h3><p>Avancez d’autant de cases que de symboles recherche. Répartissez ces cases entre les deux pistes. Un niveau comporte plusieurs cases : 2, 3, 4, 5, 6 puis 7.</p></div><div><Globe2 /><h3>Prospérité</h3><p>Gagnez un point par symbole prospérité visible, sur vos tuiles et sur la piste de pollution.</p></div></div></section>
    <section><h2>Acheter et construire</h2><p>Le prix dépend du niveau de recherche de la tuile et de votre niveau sur sa piste, énergie ou écologie : 50 € si la tuile est de niveau inférieur, 100 € si le niveau est identique, puis 100 € de plus par niveau supérieur.</p><p>Les centrales occupent les cases roses, la distribution les cases jaunes, les transports les vertes, les infrastructures les bleues. Vous pouvez recouvrir une tuile ou un bâtiment imprimé : tous ses anciens effets disparaissent. Recouvrir la ceinture verte par un transport ouvre les deux emplacements bleus situés en dessous.</p><p>Les projets spéciaux sont consommés immédiatement : ils donnent 1 ou 2 points, ou retirent jusqu’à 3 pollutions. Ils n’occupent aucun emplacement. Une dépollution par action ou projet spécial ne rapporte jamais d’argent.</p></section>
    <section><h2>Pollution et prospérité</h2><p>Les 15 cases rondes se remplissent depuis le bas ; les symboles de prospérité sont sur les cases 1, 6 et 11. Un symbole découvert ajoute un point à chaque décompte de prospérité. La 16e pollution atteint le triangle et toutes les suivantes s’y empilent : aucun gain de prospérité n’est alors possible tant que la pollution reste au moins égale à 16.</p></section>
    <section><h2>Le décompte final</h2><p>Après les deux dernières actions, appliquez dans l’ordre : deux décomptes énergie, deux écologie, un capital, un recherche et un prospérité.</p><p>Après le capital, chaque tranche complète de 300 € devient un point ; le reste est conservé. La recherche finale avance chaque piste du nombre total de symboles recherche, sans les répartir. Il n’y a pas de limite à 50 points de prospérité.</p></section>
    <section><h2>Parties personnalisées</h2><p>Le catalogue de l’atelier s’applique aux nouvelles parties personnalisées. Une partie en cours conserve son catalogue au moment du lancement. Les créations disponibles dès le départ rejoignent le marché ; les créations datées ajoutent des tours à leur décennie. Les modifications peuvent donc changer la durée, la fréquence des décomptes et l’équilibre du jeu.</p><p>La graine fixe le mélange des tuiles : un même catalogue et une même graine reproduisent le même ordre. Les parties et le catalogue sont enregistrés dans ce navigateur. L’export JSON de l’atelier contient les tuiles et leurs illustrations importées.</p></section>
    <footer className="credits"><strong>Prosperity</strong><p>Un jeu de Reiner Knizia et Sebastian Bleasdale. Illustrations du jeu original : Arnaud Demaegd et Neriac. Ystari Games, 2013.</p><p>Adaptation web non officielle. Règles issues du livret fourni par l’utilisateur ; droits conservés par leurs auteurs respectifs. Les illustrations isométriques de cette adaptation ont été générées pour cette version web.</p></footer>
  </article>;
}
